# Generated by Django 2.2.6 on 2022-01-14 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_case',
            name='index',
            field=models.IntegerField(null=True),
        ),
    ]
