# Generated by Django 3.1.2 on 2022-04-06 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0002_db_case_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=10, null=True)),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='db_api',
            name='project_folder_id',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
