# Generated by Django 3.1.2 on 2022-04-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_db_project_folder_project_folder_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_api',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='db_api',
            name='create_user',
            field=models.CharField(max_length=1000, null=True, verbose_name='创建人'),
        ),
        migrations.AddField(
            model_name='db_api',
            name='updata_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='更改时间'),
        ),
        migrations.AddField(
            model_name='db_api',
            name='updata_user',
            field=models.CharField(max_length=1000, null=True, verbose_name='更改人'),
        ),
    ]
