# Generated by Django 3.1.2 on 2022-04-29 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0010_db_project_host_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_project_host',
            old_name='project_id',
            new_name='host_folder_id',
        ),
    ]
