# Generated by Django 3.1.2 on 2022-04-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0011_auto_20220429_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_project',
            name='local_variable',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
