# Generated by Django 3.1.2 on 2022-04-29 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0012_db_project_local_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='db_project',
            old_name='local_variable',
            new_name='local_variable_id',
        ),
    ]
